### PR TITLE
few tweaks to make a functioning example.

### PR DESCRIPTION
**Pull request by bytepoet**

### CODE REVIEW

**Comment by skx** [comment]
I guess this is a change in the base-image(s) I'm building from.

Thanks for your contribution, I'll test and merge shortly.  (Been offline for the past week.)

**Comment by bytepoet** [comment]
Yeah, and I love your code, in fact I'd like to implement it into my
services "docker containers" that I spin up for customers.

Would you mind?

**Comment by skx** [comment]
I'm not 100% sure what you're asking, but certainly the intention is that the code is under an open license - so long as you don't pretend you wrote it, and share any useful improvements then you're welcome to use it.  That's the point!

I guss the result would be that your clients would be able to setup their own markdown-sharing service?  That's fine...

**Comment by bytepoet** [comment]
Yeah, the idea is that they control it almost as if it's their personal
pastebin.  They can destroy the content and the whole service once they're
done.

If you consider the continuation of development, I'd love to add it to the
lineup.

**Comment by skx** [comment]
I consider the site/service pretty much "done".  

But if you have ideas for new features then I'd be happy to hear..

**Comment by bytepoet** [comment]
Was really interested in the message expiration.

**Comment by skx** [comment]
It's easy to handle since the redis key can be made to expire.  

The complication is that I didn't want to add an extra text-field on the [create page](http://markdownshare.com/create/).  I wanted it to be simple/minimal.

If we could add an `?expires=1d` field in [the API](http://markdownshare.com/api/) then it is very very simple to add support, and that would be accepted.

**Pull request merged**
